/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 low_poly_room.glb 
Author: IsaacTheMaverick (https://sketchfab.com/IsaacTheMaverick)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-room-a6bf7976f3ac401e96907aa5b8a0c1c1
Title: Low Poly Room

SHADOWS ENABLED:
- castShadow: Model akan cast shadow ke objek lain
- receiveShadow: Model akan receive shadow dari objek lain
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Room(props) {
  const { nodes, materials } = useGLTF('/3D/low_poly_room.glb')
  
  return (
    <group {...props} dispose={null}>
      <group position={[-126.857, 16.425, 29.041]} rotation={[-Math.PI / 2, 0, 0]} scale={16.095}>
        {/* Enable shadows untuk setiap mesh */}
        <mesh 
          geometry={nodes.Cube002_UberTexture_0.geometry} 
          material={materials.UberTexture}
          castShadow
          receiveShadow
        />
        <mesh 
          geometry={nodes.Cube002_PC_Glass_0.geometry} 
          material={materials.PC_Glass}
          castShadow
          receiveShadow
        />
        <mesh 
          geometry={nodes.Cube002_Floor_0.geometry} 
          material={materials.Floor}
          castShadow
          receiveShadow
        />
      </group>
    </group>
  )
}

useGLTF.preload('/3D/low_poly_room.glb')
